# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'filter_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

import sys
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QApplication, QDialog

class Ui_FilterDialog(object):
    def setupUi(self, FilterDialog):
        FilterDialog.setObjectName("FilterDialog")
        FilterDialog.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(FilterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(FilterDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.groupBox = QtWidgets.QGroupBox(FilterDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_radioButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_radioButtons.setObjectName("horizontalLayout_radioButtons")
        self.label_compare_value = QtWidgets.QLabel(self.groupBox)
        self.label_compare_value.setObjectName("label_compare_value")
        self.horizontalLayout_radioButtons.addWidget(self.label_compare_value)
        self.radioButton_char = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_char.setObjectName("radioButton_char")
        self.horizontalLayout_radioButtons.addWidget(self.radioButton_char)
        self.radioButton_hex = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_hex.setObjectName("radioButton_hex")
        self.horizontalLayout_radioButtons.addWidget(self.radioButton_hex)
        self.radioButton_record = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_record.setObjectName("radioButton_record")
        self.horizontalLayout_radioButtons.addWidget(self.radioButton_record)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_radioButtons)
        self.lineEdit_value = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_value.setObjectName("lineEdit_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_value)
        self.verticalSpacer = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.SpanningRole, self.verticalSpacer)
        self.label_offset = QtWidgets.QLabel(self.groupBox)
        self.label_offset.setObjectName("label_offset")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_offset)
        self.horizontalLayout_offset_operand = QtWidgets.QHBoxLayout()
        self.horizontalLayout_offset_operand.setObjectName("horizontalLayout_offset_operand")
        self.lineEdit_offset = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_offset.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEdit_offset.setObjectName("lineEdit_offset")
        self.horizontalLayout_offset_operand.addWidget(self.lineEdit_offset)
        self.horizontalSpacer1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_offset_operand.addItem(self.horizontalSpacer1)
        self.label_operand = QtWidgets.QLabel(self.groupBox)
        self.label_operand.setObjectName("label_operand")
        self.horizontalLayout_offset_operand.addWidget(self.label_operand)
        self.horizontalSpacer2 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_offset_operand.addItem(self.horizontalSpacer2)
        self.radioButton_equal = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_equal.setObjectName("radioButton_equal")
        self.horizontalLayout_offset_operand.addWidget(self.radioButton_equal)
        self.horizontalSpacer3 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_offset_operand.addItem(self.horizontalSpacer3)
        self.radioButton_greater = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_greater.setObjectName("radioButton_greater")
        self.horizontalLayout_offset_operand.addWidget(self.radioButton_greater)
        self.horizontalSpacer4 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_offset_operand.addItem(self.horizontalSpacer4)
        self.radioButton_less = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_less.setObjectName("radioButton_less")
        self.horizontalLayout_offset_operand.addWidget(self.radioButton_less)
        self.horizontalSpacer5 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_offset_operand.addItem(self.horizontalSpacer5)
        self.radioButton_notequal = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_notequal.setObjectName("radioButton_notequal")
        self.horizontalLayout_offset_operand.addWidget(self.radioButton_notequal)
        self.horizontalSpacer6 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_offset_operand.addItem(self.horizontalSpacer6)
        self.radioButton_greaterequal = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_greaterequal.setObjectName("radioButton_greaterequal")
        self.horizontalLayout_offset_operand.addWidget(self.radioButton_greaterequal)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_offset_operand)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_buttons.addWidget(self.pushButton_add)
        self.pushButton_modify = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.horizontalLayout_buttons.addWidget(self.pushButton_modify)
        self.pushButton_delete = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_buttons.addWidget(self.pushButton_delete)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_buttons)
        self.pushButton_clear_all = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear_all.setObjectName("pushButton_clear_all")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButton_clear_all)
        self.horizontalLayout_apply_cancel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_apply_cancel.setObjectName("horizontalLayout_apply_cancel")
        self.pushButton_apply = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.horizontalLayout_apply_cancel.addWidget(self.pushButton_apply)
        self.pushButton_cancel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_apply_cancel.addWidget(self.pushButton_cancel)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_apply_cancel)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(FilterDialog)
        QtCore.QMetaObject.connectSlotsByName(FilterDialog)

    def retranslateUi(self, FilterDialog):
        _translate = QtCore.QCoreApplication.translate
        FilterDialog.setWindowTitle(_translate("FilterDialog", "FILTER 조건 입력"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FilterDialog", "SEQ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FilterDialog", "VALUE TYPE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FilterDialog", "VALUE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FilterDialog", "OFFSET"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FilterDialog", "OPERAND"))
        self.groupBox.setTitle(_translate("FilterDialog", "Filter 항목 정의"))
        self.label_compare_value.setText(_translate("FilterDialog", "비교 값"))
        self.radioButton_char.setText(_translate("FilterDialog", "Character 입력"))
        self.radioButton_hex.setText(_translate("FilterDialog", "HEX 입력"))
        self.radioButton_record.setText(_translate("FilterDialog", "Record 상의 값을 서로 비교"))
        self.label_offset.setText(_translate("FilterDialog", "비교 대상 OFFSET"))
        self.label_operand.setText(_translate("FilterDialog", "OPERAND"))
        self.radioButton_equal.setText(_translate("FilterDialog", "="))
        self.radioButton_greater.setText(_translate("FilterDialog", ">"))
        self.radioButton_less.setText(_translate("FilterDialog", "<"))
        self.radioButton_notequal.setText(_translate("FilterDialog", "<>"))
        self.radioButton_greaterequal.setText(_translate("FilterDialog", ">="))
        self.pushButton_add.setText(_translate("FilterDialog", "추가"))
        self.pushButton_modify.setText(_translate("FilterDialog", "수정"))
        self.pushButton_delete.setText(_translate("FilterDialog", "삭제"))
        self.pushButton_clear_all.setText(_translate("FilterDialog", "CLEAR ALL DEFINE"))
        self.pushButton_apply.setText(_translate("FilterDialog", "적용"))
        self.pushButton_cancel.setText(_translate("FilterDialog", "취소"))

class FilterDialog(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_FilterDialog()
        self.ui.setupUi(self)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    dialog = FilterDialog()
    dialog.show()
    sys.exit(app.exec())


